### ISSUE TITLE
A small change to fix the bug： No module named 'djinn_fns'

### ISSUE THREAD

**Issue by CharlieLuuke** [LLNL/DJINN#1]
Windows，py35&37
When I followed the installation tutorial, the bug "No module named 'djinn_fns'" occured after I run the example.
The solution I used is simple, In line 25 of the djinn file, change "from djinn_fns" to "from .djinn_fns".
Thanks to the author for his remarkable work, it helped me a lot.

**Comment by khumbird** [comment]
Thanks for pointing this out; this is a needed fix for py3 installs. I'm setting up a branch that is py3/tf2 compatible.
