### ISSUE TITLE
No module named 'djinn_fns'

### ISSUE THREAD

**Issue by ljpguimen** [LLNL/DJINN#4]
Hi,

We followed the installation instruction but got this error when test (attached below). Could you think of a possible reason? Anything we have to compile after the installation?

Traceback (most recent call last):
  File "djinn_classification_example.py", line 34, in <module>
    from djinn import djinn
  File "D:\Anaconda\envs\venv\lib\site-packages\djinn\djinn.py", line 25, in <module>
    from djinn_fns import tree_to_nn_weights, tf_dropout_regression, \
ModuleNotFoundError: No module named 'djinn_fns'

**Comment by khumbird** [comment]
Hi, try changing: "from djinn_fns" to "from .djinn_fns" in djinn.py
This is necessary for python3.
If you could let me know if the above fix works for you, and which python version you are running, that would be very helpful so I can include necessary changes into the source. Please let me know if it does *not* work as well, and I'll get back to you.

**Comment by ljpguimen** [comment]
> Hi, try changing: "from djinn_fns" to "from .djinn_fns" in djinn.py
> This is necessary for python3.
> If you could let me know if the above fix works for you, and which python version you are running, that would be very helpful so I can include necessary changes into the source. Please let me know if it does not work as well, and I'll get back to you.

That fix it, thanks! I'm using python3.6
